### PR TITLE
3.2.0

### PR DESCRIPTION
**Pull request by asterized**
Closes # 

## 📑 Description

Added support for async and done code refactoring.

Added async

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by asterized** [comment]
many commits

**Comment by interrrp** [comment]
But you have not updated the documentation as required?! Unacceptable!

**Comment by Sas2k** [comment]
Hello, @SomeHybrid your code on the async support looks great, @1nter-p well there isn't any documentation, the documentation like thing is the Readme's Usage section

**Comment by Sas2k** [comment]
If there isn't anything else to add I will pr this in.

**Comment by Sas2k** [comment]
If there isn't anything else to add I will pr this in.

**Comment by asterized** [comment]
Updated readme for async usage

**Comment by Sas2k** [comment]
Ok, now I will PR it

**Comment by interrrp** [comment]
this literally doesn't work, @SomeHybrid did you even test it?

**Pull request merged**
